version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lqta4r
      - MONGO_INITDB_ROOT_PASSWORD=paKxjNzdgkX74EJW7RkpuNAuh
    volumes:
      - db:/data/db
    restart: unless-stopped

  app:
    image: lqta4r/app:latest
    container_name: app
    ports:
      - "80:80"
    environment:
      - MONGO_URL=mongodb://lqta4r:paKxjNzdgkX74EJW7RkpuNAuh@mongo:27017
      - HOST=0.0.0.0
      - PORT=80
    depends_on:
      - mongo
    restart: always

volumes:
  db: